<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>

	 <StartupObject>lab4.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MaterialSkin.2" Version="2.3.1" />
    <PackageReference Include="MSTest" Version="4.1.0" />
    <PackageReference Include="MSTest.TestFramework" Version="4.1.0" />
    <PackageReference Include="NUnit" Version="4.5.0" />
  </ItemGroup>

</Project>